### ISSUE TITLE
LPPC sectors need unique CPDLC logons

### ISSUE THREAD

**Issue by pinatacolada** [pinatacolada/topskylppc#68]
who keeps CPDLC open? Do both open? With what callsign? It's a mystery, nobody knows

**Comment by mjpikat** [comment]
Yes, all ACC sectors that would like to use CPDLC have to have own login. For the main CPDLC callsign I suggest to use bandbox position - LPPC_CTR with CPDLC LPPC (and if any other split sector that has it's frequency, too). For others like LPPC_E etc you can use own codes, just make sure the code doesn't overlap with any other ICAO airport (to avoid confusion). For example LPPC_E CPDLC could be LPCE or LPZE.

**Comment by pinatacolada** [comment]
@becas22

**Comment by becas22** [comment]
It is what it is…

Enviado do Correio<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: pinatacolada <notifications@github.com>
Enviado: Thursday, May 7, 2020 9:05:58 PM
Para: pinatacolada/topskylppc <topskylppc@noreply.github.com>
Cc: becas22 <benyreis@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [pinatacolada/topskylppc] need to figure out what the heck happens if LPPC_E and W are open at the same time in regards to CPDLC (#68)


@becas22<https://github.com/becas22>
